import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import AppSidebar from '@/components/common/app-sidebar';
import MessageInput from '@/components/message-input';
import MaxWidthWrapper from '@/components/max-width-wrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SidebarProvider className='relative'>
          <AppSidebar />
          <SidebarTrigger className='fixed left-4 top-4 z-10' />
          <main className='relative grow-1 px-2 overflow-auto overscroll-none min-h-svh max-h-svh'>
            <MaxWidthWrapper className='flex flex-col justify-between h-full'>
              {children}
              <MessageInput className='sticky mx-auto bottom-0 w-full' />
            </MaxWidthWrapper>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
